name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'HcpVaultSecretsConfigProvider.sln'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0

    - name: Restore dependencies
      run: nuget restore $SOLUTION

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore

    # - name: Run tests
    #   run: dotnet test /p:Configuration=$env:BUILD_CONFIG --no-restore --no-build --verbosity normal